project_name: ippi

builds:
  - dir: ippi
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}
    files:
      - LICENSE
      - README.md

nfpms:
  - file_name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Arch }}"
    vendor: "Cloud Unpacked"
    homepage: "https://www.CloudUnpacked.com"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A simple public IP address API"
    license: MIT
    formats:
      - deb
    bindir: /usr/bin

dockers:
- image_templates:
  - "ghcr.io/cloud-unpacked/ippi:v{{ .Version }}"
  - "ghcr.io/cloud-unpacked/ippi:{{ if .IsSnapshot }}staging{{ else }}v{{ .Major }}.{{ .Minor }}{{ end }}"
  - "ghcr.io/cloud-unpacked/ippi:latest"
  dockerfile: goreleaser.Dockerfile

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"

announce:
  skip: "{{ gt .Patch 0 }}"
  mastodon:
    enabled: true
    server: "https://nanobyte.cafe"
